---
# Tasks for setting up a simple backup
- name: create backup directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ xwiki_backup_log_dir }}"
    - "{{ xwiki_backup_script_dir }}"
    - "{{ xwiki_backup_dir }}"

- name: create backup script
  template:
    src: backupscript.sh.j2
    dest: "{{ xwiki_backup_script_dir }}/xwiki_backup.sh"

- name: install rsync
  package:
    name: rsync
    state: present
  when: xwiki_backup_remote_location is defined

- name: create ssh directory
  file:
    path: /root/.ssh
    mode: 0700
    state: directory
  when: xwiki_backup_ssh_key is defined

- name: copy ssh key to root user for backups
  copy:
    src: "{{ xwiki_backup_ssh_key }}"
    dest: "{{ xwiki_remote_backup_identity_file }}"
    mode: 0600
  when: xwiki_backup_ssh_key is defined

- name: add remote backup server to known hosts file
  known_hosts:
    hash_host: true
    key: "{{ xwiki_backup_remote_host_public_key }}"
    name: "{{ xwiki_backup_remote_host_name }}"
    state: present

- name: Set cronjob for automated backup
  cron:
    name: xwiki backup
    job: >-
      bash {{ xwiki_backup_script_dir }}/xwiki_backup.sh &>>
      {{xwiki_backup_log_dir}}/xwiki_backup.log
    state: present
    minute: "{{ xwiki_backup_cron_minute }}"
    hour: "{{ xwiki_backup_cron_hour }}"
    day: "{{ xwiki_backup_cron_day }}"
    weekday: "{{ xwiki_backup_cron_weekday }}"
    month: "{{ xwiki_backup_cron_month }}"
